import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Header from "./_components/Header";
import { TRPCReactProvider } from "~/trpc/react";
import { redirect } from "next/navigation";
import { auth } from "~/server/auth";
import { SidebarProvider, SidebarInset, SidebarTrigger } from "~/shared/ui/sidebar";
import AppSidebar from "./_components/AppSidebar";
import { api } from "~/trpc/server";

export const runtime = "nodejs"

export const metadata: Metadata = {
  title: "Test",
  description: "Generated by Anastasiia",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  if (!session) {
    redirect("/sign-in");
  }

  const dataRooms = await api.dataRoom.list();

  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <SidebarProvider>
            <AppSidebar initialData={dataRooms} />
            <SidebarInset>
              <Header />
              <SidebarTrigger />
              {children}
            </SidebarInset>
          </SidebarProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}